server:
  port: 8491
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          # git仓库的地址
          uri: https://github.com/LittleBaronHome/springcloud-config
          # git仓库地址下的相对地址，可以配置多个，用,分割。
          search-paths: springcloud-config
          username: qiao_jiyuan@163.com
          password: yuanyuan8513.2
  # /{application}/{profile}[/{label}]
  # /{application}-{profile}.yml
  # /{label}/{application}-{profile}.yml
  # /{application}-{profile}.properties
  # /{label}/{application}-{profile}.properties
  # 以springcloud-config-dev.properties为例，它的application是springcloud-config，profile是dev，label是分支的意思，
  # 如果只有一个主分支，可以不写，默认会访问master分支，client会根据填写的参数来选择读取对应的配置。

  # spring.profiles.active=native，本地存储配置的方式 Config Server会默认从应用的src/main/resource目录下检索配置文件

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8090/eureka/